package model;

import java.util.Random;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 28 16:02:10 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    public void startProcess(String pName) {
        Random rnd = new Random();
        ViewObjectImpl dpvo = this.getDemoProcessView1();
        Row newRow = dpvo.createRow();
        int nextNumber = rnd.nextInt(100) + 1;
        newRow.setAttribute("Pid", nextNumber);
        newRow.setAttribute("Column1", pName);
        newRow.setAttribute("Pstatus", "RUNNING");
        dpvo.insertRow(newRow);
        getDBTransaction().commit();

        //-------Simulate the long process---------

        for (int i = 0; i <= 30; i++) {
            System.out.println("Thread Name = " + pName + " , Count = " + i);
            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
            }
        }
        
        Key key = new Key(new Object[]{nextNumber});
        Row[] row = dpvo.findByKey(key, 1);
        row[0].setAttribute("Pid", nextNumber);
        row[0].setAttribute("Column1", pName);
        row[0].setAttribute("Pstatus", "FINISHED");
        getDBTransaction().commit();
    }

    /**
     * Container's getter for DemoProcessView1.
     * @return DemoProcessView1
     */
    public ViewObjectImpl getDemoProcessView1() {
        return (ViewObjectImpl) findViewObject("DemoProcessView1");
    }
}

